apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reconciler-rolebinding
  namespace: test-ns
subjects:
- kind: ServiceAccount
  name: ns-reconciler-test-ns-main-4
  namespace: config-management-system
roleRef:
  kind: Role
  name: reconciler-role
  apiGroup: rbac.authorization.k8s.io
