apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-ns
  name: reconciler-role
rules:
- apiGroups: [""]
  resources: ["roles"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
